export const skills = [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "TeamWork",
    "Java Script ECMAScript 6",
    "React.js",
    "React Hooks",
    "Custom Hooks",
    "React Router",
    "Redux-Saga",
    "Redux Toolkit",
    "Working with API",
    "Promises, Async/Await",
    "Fetch/Axios",
    "Error handling: Try/Catch",
    "Styled Components",
    "LocaleStorage",
    "CSS Flexbox, Grid",
    "Media Queries Level 4",
    "Normalize.css",
    "Animation",
    "Keyframes",
    "CSS BEM convention",
    "Immutability",
    "Markdown",
    "GitHub Pull Requests & Review",
    "Git",
    "JSX",
    "Babel",
    "Webpack",
    "NPM",
    "Scrum",
    "Figma",
    "Trello",
];

export const nextSkills = [
    "TypeScript",
    "Next.js",
    "Supabase",
    "Vercel",
    "Tailwind CSS",
    "Flowbite",
];

